### ISSUE TITLE
As a user I can call an external REST Service from a TP Function

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#1004]
## Context
Several users have requested the ability to call external functions over REST from TP functions. This allows the TP functions to off-board complex or expensive computation to a centrally or peer hosted service.

## Expected Behavior
TP function should be able to make a POST request to a REST service, passing in asset, participant, concept or transaction data.

The result of making the REST request should be available to the TP function for further processing or persistence. This includes the service returning the JSON for an asset/participant/concept to be processed by the TP function (requiring deserialisation).

## Idempotency and Consensus

The result of the REST request should be a pure function (idempotent) to ensure that all peers get the same results with the same inputs. If this restriction is honored then the risk of consensus failure is minimised.

*Each* peer will make a call to the REST service.

## CORS

HTTP requests from the web browser will need to be CORS compliant. This requires the server be setup to receive the OPTIONS method and return appropriate headers.

## Docker Network Resolution

HTTP request from the HLF chain code container require DNS resolution and network are in place. For example, with the default Docker container one cannot use http://localhost as this does not resolve to the host machine inside the Docker container. The easiest workaround is to use a DNS name that is publicly resolvable.

### Questions / Issues

- Do we need to allow the peers to have different URLs, or can they configure DNS to resolve names differently within their network?

## Tasks

- [x] Write Go code to extend the Fabric runtime
- [x] Define the HTTPService
- [x] Add the `post` method to the runtime API
- [x] Expose the serialiser to the TP function, so that assets/participants returned by the REST service can be converted back into resources
- [x] Write the hlfv1 implementation
- [x] Write the hlf 0.6 implementation
- [x] Write the web implementation
- [x] Write the embedded implementation
- [x] Documentation
- [x] Unit tests
- [x] System tests

## Sample TP Function

```
/**
 * Handle a POST transaction, calling OpenWhisk
 * @param {org.acme.sample.PostTransaction} postTransaction - the transaction to be processed
 * @transaction
 */
function handlePost(postTransaction) {

  return post( 'https://openwhisk.ng.bluemix.net/api/v1/web/daniel.selman_dev/default/HyperledgerComposerAction.json', postTransaction)
      .then(function (result) {
        postTransaction.asset.value = 'Count is ' + result.body.sum;
        return getAssetRegistry('org.acme.sample.SampleAsset')
          .then(function (assetRegistry) {
            return assetRegistry.update(postTransaction.asset);
          })
          .then(function (assetRegistry) {
            return "Asset updated with value " + result.body.sum;
          });
      });
}
```

Sample OpenWhisk implementation:

```
function main(postTransaction) {
	return { "count": postTransaction.a + postTransaction.b };
}
```

Sample Node-RED Flow:

```
[{"id":"c12d8254.dd6aa","type":"http in","z":"f32ae93b.8cb9a8","name":"","url":"/compute","method":"post","swaggerDoc":"","x":242.5,"y":155,"wires":[["3a9814a8.94a0e4"]]},{"id":"3a9814a8.94a0e4","type":"function","z":"f32ae93b.8cb9a8","name":"","func":"msg.payload.sum = msg.payload.a + msg.payload.b;\nreturn msg;","outputs":1,"noerr":0,"x":367.5,"y":216,"wires":[["91d40e82.cb6d18"]]},{"id":"c60e4747.9e336","type":"debug","z":"f32ae93b.8cb9a8","name":"","active":true,"console":"false","complete":"payload","x":740.5,"y":115,"wires":[]},{"id":"91d40e82.cb6d18","type":"change","z":"f32ae93b.8cb9a8","name":"Set Headers","rules":[{"t":"set","p":"headers","pt":"msg","to":"{}","tot":"json"},{"t":"set","p":"headers.content-type","pt":"msg","to":"application/json","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":577,"y":215,"wires":[["b915014c.e2a61","c60e4747.9e336"]]},{"id":"b915014c.e2a61","type":"http response","z":"f32ae93b.8cb9a8","name":"","x":769,"y":213,"wires":[]}]
```

Sample Node-Red CORS Configuration:

```
    httpNodeCors: {
        origin: "*",
        methods: "POST",
        credentials: true
    },
```
