### ISSUE TITLE
Update vehicle-lifecycle-demo to show events, queries and ACLs

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1084]
To make more of the demo real we need to do the following things

- [x] Update to use events - > use composer in node (node red)
- [ ] Update orders to use queries
- [ ] update regulatory to use historian and query
- [ ] update suspicious vehicles to use queries
	— > make blockchain detect suspicious events i.e mileage

- [ ] Need something to show acls
	—> Different log in for dashboard to show being able to cancel an order if superuser

**Comment by fenglianxu** [comment]
Story #994 will deliver the query features for this epic.

**Comment by sstone1** [comment]
Replaced by CIP #3130.
