### ISSUE TITLE
The grand master plan for v0.16.0

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1390]
This is an issue tracking all of the high-level issues that we believe we need to solve before we can declare a v0.16.0 release of Hyperledger Composer. For more information on the release planning, see the email to the mailing list on this subject: https://lists.hyperledger.org/pipermail/hyperledger-composer/2017-November/000044.html

We would appreciate any community feedback on this list and all items are up for discussion.

Note that the list is unordered in terms of priority.

- [x] As a contributor, I need to model core types in a system namespace #920
- [x] As a user, I can perform complex queries against resources in a business network #543
- [x] As a user, I can see notifications of published events in the playground #998
- [x] As a user I can protect my REST APIs using authentication and authorization #142 
- [x] As a business network developer, I can enforce system level access control #722
- [x] As a user, I can view, issue, and revoke identities for participants in a business network #817
- [x] composer issue identity needs to be able to provide affiliation #606
- [x] Implement controllable logging for chaincode and runtime #669
- [x] As a user I can generate sample data that excludes optional properties #796
- [x] As a user, I want to perform complex queries when using the REST APIs #921
- [x] As a user, I can subscribe to events (using webhooks or websockets) from the REST server #1177
- [x] As a network starter, I can specify a HLF v1.0 endorsement policy during network start #1251
- [x] As a user, identities are mapped to participants using public key signatures #1291
- [x] As a network manager, I can install the Composer runtime on my Blockchain nodes #1292
- [x] As a network starter, I can start a business network in a consortium #1293
- [x] As a contributor, I no longer have to maintain support for Fabric v0.6 #1535

- [x] Introduce Composer ID Cards to handle deployment of multiple business networks to a connection profile #902
- [x] As a user of a business network, I can view a record of all significant business events #55
- [x] As a user, I can easily share connection profiles between users and systems #935
- [x] As a user, I should not have to specify an enrolment secret if I have already enrolled #937
- [x] As a user, I can manage connection profiles using the CLI #939
- [x] As a network starter, I can bind an initial set of identities to participants at deployment time #670
- [x] As a user, I can link the Composer transaction to the underlying Blockchain transaction #936
- [x] As a user, when I issue a new identity I am not mislead into treating the secret as a password #2056
- [x] As a user, I want to run Composer using Node.js v8.x #2100 
- [x] As a user, I can import existing identities into my REST server wallet #2072
- [ ] As a user, I can import/export identities between all Composer components #943

**Comment by harrika1982** [comment]
To get to active status,  Composer needs contributors from at least three different organizations.

**Comment by smartapp-ep** [comment]
for a production business network, currently it's only possible for micro version runtime upgrade, 1) will minor or even major upgrade likely in the road map? 2) if not, what would be the suggestions? perhaps even manual & customized scrips or high level instructions for migration or import of existing data? but at least there's a path or option ahead for production network? or any workaround? 3) before anything feasible released, what would you suggest? appreicate any advice (i asked similar question in the chat room and was directed to here but couldn't find my answer)

**Comment by smartapp-ep** [comment]
Currently network upgrade is only possible with micro version.  When we move from prototype to production, the ability or options for production business network to upgrade runtime and import old data will be one of the critical barrier we are faced with.

Is this in the road map? is [2097](https://github.com/hyperledger/composer/issues/2097) only for micro version or also includes minor and major? 

If this is unlikely in forseeable roadmap, what'd be the high level suggestion or work around? i think at least application developers can develop some db scripts if the schema change of each minor release is provided? or what would be the advice? look forward to any feedbacks.

**Comment by sstone1** [comment]
Closing as v0.16.0 was delivered.
