### ISSUE TITLE
As a user, I can use a common connection profile format between Fabric v1.0 and Composer

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2023]
As per https://jira.hyperledger.org/browse/FAB-5363
this describes a new type of connection profile format that hyperledger fabric applications can use in order to interact with a fabric. The node sdk plans to add support for this connection profile format into v1.1 (need to confirm this will definitely be there though) and the idea being that it can make intelligent interactions with the fabric (for example invoke vs instantiate vs query)

We should exploit this coming feature (referred hereafter as CCP)

## Tasks required
- [x] Playground support for the creation of a single Org CCP
- [x] Runtime support for CCP
- [x] Composer-Tools/DevServer deliver a CCP

**Comment by sstone1** [comment]
Actually a significant amount of work to be done on this one - it's not just runtime support, but also playground support to build the things in the first place.

**Comment by davidkel** [comment]
Questions
- Do we continue to support the old format in the client code ?
- The new format allows for multiple channels do we want to support multiple channels in the API as per #2103 ?

Statements
- This is a far more wordy and intricate connection profile, so would not expect users to create by hand, so we will need to create one for our development server and also ensure other fabrics also have these documents that we can test.
- The implementation for parsing and using these is coming in V1.1 of the node SDK (hopefully) but not available yet and may not work with Fabric 1.0.x implementations if any protocols change from 1.0 to 1.1.

**Comment by sstone1** [comment]
> Do we continue to support the old format in the client code
No, bin the old format and only support the new format 👍

**Comment by davidkel** [comment]
Implemented a prototype in the runtime, however it has shown up some missing capabilities in the current node sdk implementation, combined with the fact that the current npm module is not upto date with the master branch (ie it's missing some implemented capabilities which we would exploit).

**Comment by davidkel** [comment]
Example of a CCP for our fabric dev server (yaml format)
```
name: "composer-devserver"
x-type: "hlfv1"
x-loggingLevel: info
description: "The network to be in if you want to stay in the global trade business"
version: 1.0.0

# this section has to be added in for the node sdk to work out what to select.
client:
  organization: Org1
  connection:
    timeout:
     peer:
      endorser: 3s
      eventHub: 3s
      eventReg: 3s
     orderer: 3s

  credentialStore:
    path: "/home/ubuntu/.composer-credentials"
    cryptoStore:
      path: "/home/ubuntu/.composer-credentials"
    wallet: wallet-name

channels:
  composerchannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com

orderers:
  orderer.example.com:
    url: grpc://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      grpc-max-send-message-length: 15

peers:
  peer0.org1.example.com:
    url: grpc://localhost:7051
    eventUrl: grpc://localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.http2.keepalive_time: 15

certificateAuthorities:
  ca.org1.example.com:
    url: http://localhost:7054
    registrar:
       enrollId: admin
       enrollSecret: adminpw
    caName: ca.org1.example.com
```
There are a couple of things to note
- The client section is required as we need to know what organisation the client is part of so that it's possible to determine, the CA Server, the MSPId, Which event hubs to connect to

**Comment by davidkel** [comment]
There will be no support provided to migrate an old connection profile to the new format within composer. We could offer something as a composer-tools type soln if there is time.

**Comment by davidkel** [comment]
@sstone1 do you want the embedded connection profile to look like
```
{ 'x-type': 'embedded'} 
```
to be consistent with the CCP and break everyones unit tests or do you want to keep it as
```
{type: 'embedded'}
```
?

**Comment by awjh-ibm** [comment]
Form for allowing the user to define their business network

![create a bn form](https://user-images.githubusercontent.com/31732124/32282937-e7749938-bf1a-11e7-962b-5b5f996a4713.png)

Add certificate form (remove removes certificate that is loaded)

![add certificate popup](https://user-images.githubusercontent.com/31732124/32283011-22a2dec0-bf1b-11e7-8e70-01946b52adf1.png)

@winslet can you provide feedback on the formatting for the above?

**Comment by winslet** [comment]
had a chat with @awjh-ibm and we have agreed some minor changes to the above:

![img_3091](https://user-images.githubusercontent.com/13980028/32445008-5a127494-c2fc-11e7-8fd7-98297c694914.jpg)
