### ISSUE TITLE
As a user I would like to decorate my model elements with metadata

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#2157]
## Context
For extensibility it would be useful to be able to decorate the elements of a composer model with metadata (aka annotations). Decorators should be supported on: assets, participants, transactions, events, concepts, properties and relationships. The model should support 0..N decorations on each element type. Note that only a single instance of a decorator is allowed on each element type. I.e. it is invalid to have the `@bar` decorator listed twice on the same element.

These annotations should be accessible at runtime via the `ModelManager` introspect APIs. This would allow external tools and utilities to use the Composer Modelling Language (CTO) file format to describe a core model, while decorating it with sufficient metadata for their own purposes.

## Design Proposal

Support a decorator syntax similar to the [JavaScript syntax for decorators](https://www.sitepoint.com/javascript-decorators-what-they-are/).

The proposed syntax for CTO files is:

```
@foo("arg1", 2)
participant Buyer extends Person {
}
```

This adds the `foo` decorator to the `Buyer` participant, with "arg1' and 2 passed as arguments to the decorator.

Similarly decorators can be attached to properties, relationships and enumerated values.

## Decorator Arguments

Decorators may have an arbitrary list of arguments (0 or more items). Argument values must be strings, numbers or booleans.
## APIs

The following APIs will be added:

- `ClassDeclaration.getDecorators() (Decorator[])`
- `ClassDeclaration.getDecorator(name) (Decorator)`
- `Property.getDecorators() (Decorator[])`
- `Property.getDecorator(name) (Decorator)`

The `Decorator` class has the following methods:

- `getName() (string)`
- `getArguments() (object[])`

This allows the developer to retrieve the 3rd argument to the `foo` decorator attached to the myField property of a class declaration:

```
const val = myField.getDecorator('foo').getArguments()[2];
```

## Valid Examples

```
namespace org.acme

@baz("foo","bar", 2, true, -2.5, 100.3)
@big
@small()
asset foo {
}

asset Bare {
}

@baz()
asset foo {
  @doo()
  o String dan

  @diz(true)
  --> Blah goo
}

enum STATUS {
    @baz(true,false)
   o FOO
}

@bar()
participant User {
}

@biz
event Stuff {
}

@bar(1.3)
transaction Blah {
}

@bar
concept Foo {
  @bar("123")
  @small
 o String twee
}
```

## Compatibility

CTO file format (grammar) changes and API changes will be backwards compatible.

## Test Impact

Test impact is expected to be small. New unit tests will be added to composer-common.

## Documentation Impact

Documentation impact is expected to be small. Additional documentation for the CTO format will be added.

## Tasks

- [x] Extend the CTO grammar
- [x] Add new introspect APIs
- [x] Semantic validation for uniqueness contraint on decorator name
- [x] Add unit tests
- [x] Extend existing CTO file format documentation

**Comment by sstone1** [comment]
@dselman looks great! Have you considered modelling the decorators themselves?

```
decorator bar {
  o String foo optional
}

@bar
concept Foo {
  @bar("123")
 o String twee
}
```

That would give us namespacing for the decorators and checked types for the arguments.

**Comment by dselman** [comment]
I did briefly consider modelling the structure of the decorators. It seemed like overkill, but seeing your example I can see the utility. It would allow us to publish libraries of the "standard" decorators that we want people to use, and `import` them into a model file.

Let's see how these get used and then we should be able to add models for them in a fairly backwards-compatible way.

**Comment by pradeeppadmarajaiah** [comment]
@dselman , Could you please provide the complete samples, on how it works.

**Comment by etrn** [comment]
@dselman 
Hi Dan,
I am quite new to Hyperledger Composer and I really need your help!
I need an asset that would be defined dynamically with N amount of properties which aren't known at this moment and would be sent in a request from the Angular app.

I assume that this could be done by using decorators in the modeling language, but I didn't find any examples that fully explains how to use them including how should I create the asset in the logic-file.

To be more clear I need something like this as a result:

```
asset $CustomNameFromFrontEnd {
o String id
o $TypeFromFrontEnd1 $PropertyNameFromFrontEnd1
o $TypeFromFrontEnd2 $PropertyNameFromFrontEnd2
…
o $TypeFromFrontEndN $PropertyNameFromFrontEndN
}
```
I would really appreciate if you could help me with an example how should I describe the asset in .cto file and how should I implement asset creation in the logic.js file.

**Comment by jt-nti** [comment]
@etrn I see you've asked this on Stack Overflow as well, which is a much better place for the question https://stackoverflow.com/questions/50698774/decorators-in-hyperledger-composer-modeling-language
