### ISSUE TITLE
Overhaul Protractor Playground Test Suite

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2166]
The introduction of ID cards, with the swap to npm downloads managed to completely nuke the existing Protractor test suite, and currently we are only validating that Playground will build and deploy.

This should be taken as an opportunity to overhaul the manner in which the UI tests are performed/driven. In particular we should:

- [ ] be scenario based
- [ ] use async/await, since Protractor is removing the internal flow control
- [x] establish a 'test mode' on the Playground API to remove a dependancy on npm when retrieving samples

Based on the above the proposal is to use Cucumber to drive Protractor based interactions. The step files will relate to UI components, and we can interact with standard Protractor code, using the async/await syntax. This will let us drive expected user scenarios instead of exhaustively testing all possible interactions, thereby giving the greatest return on build time.
