### ISSUE TITLE
As a Java developer, I want a native java sdk for composer on client side

### ISSUE THREAD

**Issue by xuanyue202** [hyperledger/composer#2182]
## Context
This involves two parts: a tool that can convert a java class from/to cto asset/concept/participant/transaction models, and a high-level sdk to operate composer on client side based on fabric-sdk-java.

For the first part, some work has already been done in the current composer (having a javavisitor for modelFile). The other direction (from Java to CTO) remained to be implemented. Moreover, it is desirable to extend the definition of Java model class using annotation. For example, 

```
@Asset
public class SampleAsset {
	@DataField(primary = true)
	public String id;

	@DataField
	public String name;

	@DataField
	public String type;
	
	@Pointer
	public SampleUser owner;
}
```

For the second part, similar interface to composer-client should be designed.

I know this might be a low priority feature for composer, but it is very crucial for Java application developer. I (and my team) will be very happy to help on this if the community think this is useful.

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sstone1** [comment]
The Java to CTO generator part of this issue seems sensible and I'd happily accept that. For the code sample above, the annotations don't match up with the names we use for those things in Composer - `DataField` (?) is really `Property`, and `primary` (?) is `identifier`.

This is for the Java SDK for Composer part of the issue:

My team isn't going to do this work any time soon. JavaScript is the current priority for us, and we have a lot more features to work on that we think are more important before we'd ever get to adding support for other languages.

Note that today you can use Swagger Codegen in conjunction with the REST API to build a Java SDK for a business network. It means you have to use the REST server, but is better than nothing and provides Java developers with _a_ way to interact with a business network from Java.

That being said, I'd love to see native support for Java (and other languages for that matter), on both the client side for developing applications and maybe even for transaction processor functions on the Blockchain.

However, I will point out there is a _huge_ amount of work to get this into a shape which we would consider accepting, particularly around testing. Unless the code is fully tested to the same level as the JavaScript code, with both unit and system tests, I for one would not be happy accepting it into the codebase.

There would also be the question of ongoing maintenance of the Java code and who would do that work. Once it is there _somebody_ (again, unlikely to be my team) has to keep it up to date with the new features and bug fixes going into the JavaScript codebase, otherwise it will get out of date quickly and will be perceived as bad quality.

**Comment by sstone1** [comment]
@dselman @caroline-church FYI

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
