### ISSUE TITLE
The grand master plan for v1.0

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2705]
This is an issue tracking all of the high-level issues that we believe we need to solve before we can declare a "v1.0" release of Hyperledger Composer. Note that such a release may not be called "v1.0", depending on our progress to active status.  For more information on the release planning, see the email to the mailing list on this subject:  https://lists.hyperledger.org/pipermail/hyperledger-composer/2017-November/000044.html

We would appreciate any community feedback on this list and all items are up for discussion.

Note that the list is unordered in terms of priority.

- [x] The grand master plan for v0.16.0 #1390
- [x] As a user, I can use a common connection profile format between Fabric v1.0 and Composer #2023
- [ ] Use npm shrinkwrap (or fix version numbers) to ensure releases remain strong and stable #651
- [x] As a contributor, I want Composer to run under Node.js on Hyperledger Fabric v1.1 #61
- [ ] As a user, I can easily perform problem determination on Composer solutions #2096
- [ ] As a user, I can safely migrate my Composer solutions to newer versions of Composer #2097
- [ ] As a user, I have access to performance reports #2163 

- [ ] #3160 Native Fabric Deployment

**Comment by davidkel** [comment]
Proposed candidates for consideration to be included
- [ ] As a system administrator I need the composer-rest-server to tolerate unavailable peers #2799 
- [ ] An implementation as a result of #2186

**Comment by davidkel** [comment]
The following have either been abandoned or a tech preview controlled by feature flags so will not be required for the 1.0 release
 HLF 1.1 Chaincode lifecycle enhancements #2378
 HLF 1.1 feature to distinguish between client and server certificates #2377
