### ISSUE TITLE
Playground Performance

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#2847]
The performance and perceived performance of playground needs to improve. This is a list of things that would make this better

- [ ] Speed up initial loading time
- [ ] When deploying a business network show more stages
- [ ] When submitting a transaction show more stages
- [ ] Add in busy status for connecting to web version
- [ ] Add in busy status for deploying/update web version business network
