### ISSUE TITLE
Proposed fixes for 0.16.1

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2913]
Initial set of fixes for the stable release:

- [x] Bump version to 0.16.1! #2913

- [x] License link is not configurable #2882

- [x] Login header displays name of last business network connected to #2903 

- [x] Publish stable, 0.16.x, documentation #2886

- [x] Publish stable, 0.16.x, web playground #2961

- [x] Unnecessary code to get playground version #2936 

- [x] Make loading page configurable #2949

- [x] Suggested re-shuffle of the Installing steps #2880 - plus associated changes in #2879 and 3ffef85ae85053be94b76bddd025c6880ea2e9bd

- [x] Make the modal close colour changeable by CSS #2957

- [x] CSS tweak to remove unnecessary line height for docker link #2933

**Comment by mbwhite** [comment]
Would also propose https://github.com/hyperledger/composer/issues/2878 be added to this

**Comment by awjh-ibm** [comment]
Request that #2949, #2957 and #2933 are included in this release

**Comment by winslet** [comment]
- [ ] Fix for close icons https://github.com/hyperledger/composer/pull/2960

- [ ] Header CSS fix #2933 

- [ ] Docs removal of single line installer https://github.com/hyperledger/composer/pull/2916 <-- please confirm

**Comment by EdMoffatt** [comment]
We should also include #2920 - it goes hand in hand with 2916, and cleans up the structure of pages that we will be linking to from Playground, plus it removes some out of date diagrams that we'd be best off not having in our stable docs (they tell you to run commands you shouldn't be running anymore ;) ).  Would be very useful to get this into the stable release so that we can update to the same links in the unstable and stable Playgrounds and avoid having that diverge too early :)

**Comment by jt-nti** [comment]
Everything is in 0.16.x so just need to make sure that everything but the version change is in master as well!

**Comment by jt-nti** [comment]
See #3018 for 0.17.x release
