### ISSUE TITLE
Hyperledger Composer 0.17.0 release

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3018]
- [ ] Support npmrc files #2921 
- [ ] Travis build changes to support multiple branches #3015
- [ ] Common Connection Profile #2023 
- [ ] remove the 1 line installer
- [ ] Pin VLD demo to 0.16.2
- [ ] Update documentation for CCP
- [ ] Update dev fabric server for v11 with new Connection Profile
