### ISSUE TITLE
As a user, I can predictably understand the performance of Composer

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3125]
## Abstract

Provide a series of test reports produced from the results of a test framework that may enable a user to infer expected performance metrics for their own business networks or to run their own performance tests in the test framework.

## Motivation

The performance of Composer needs to understood both from a user and contributor perspective. As a user, I would like to know the expected performance (in terms of throughput and response times etc) that my business network will be capable of, and as a contributor I need to know that the code I deliver does not negatively impact performance.

Currently there is a [Composer plugin for Caliper](https://github.com/nklincoln/caliper), that may be used to run tests on [Composer 0.16.x](https://github.com/nklincoln/caliper/tree/add-composer) and [0.17.x](https://github.com/nklincoln/caliper/tree/composer-fabric-preview) branches; this is however a manual process. This framework needs to be extended and integrated into an automated system to enable monitoring of Composer performance and the generation of data for performance reports.

## Specification

I propose that we:
- Document how to use the existing Composer plugin for Caliper to run a performance test on either an existing sample/micro-test, or to use it to test your own business network.
- Enhance the Composer code base logging in 0.17.x to enable performance trace (this trace exists in the 0.16.x branch)
- Conditionally enable the use of [AppMetrics](https://github.com/RuntimeTools/appmetrics) within the tests to monitor chaincode
- Configure all performance tests to be run overnight on a dedicated test machine
  - Flag any performance regressions that are detected
- Publish performance results observed for:
  - Different Sample Business Networks
  - Different levels of Composer
  - Different Fabric topologies

## Rationale – why are we proposing to do it this way?

We already have a test framework for performance testing of Composer within Fabric, we should continue to extend this to cover the above specification.

## Backwards Compatibility

The resulting framework will need to be capable of testing different versions of Composer on different Fabric levels and topologies. For instance we will want to be able to test Composer v0.16.x on Fabric 1.0.x, and Composer v0.17.x on Fabric 1.1.x. There is added complexity between the v0.17.2 and v0.17.3 levels which include a jump from the preview and alpha fabric drivers.

### Readiness Criteria
  - Whilst all performance tests should be runnable on a dedicated machine, work can commence on all framework items and target tests on a local machine
 - New framework required to spawn the tests and monitor for performance regressions for tests running in the main test harness

### User Acceptance Criteria
  - Anyone should be able to read a given performance report for a set of sample networks, and make a comparison to their own metric to gain an understanding of an expected performance
 - Anyone should be able to use a readme to clone the test framework, and locally run specific tests on their own business network to get actual results
 - Developers of Composer should be informed if their code delivery impacts performance
 
### Assumptions
 - Dedicated hardware will be available to run all the performance tests
 - Failure of the above would require all performance testing to be run on a local machine, which is likely to result in inconsistent results

### Exit Criteria
 - User acceptance criteria filled

## Implementation

I propose that I will implement this as described above and deliver via the following series of pull requests:
- [x] Documenting how to run performance tests using the Composer plugin for Caliper (#3310)
- [x] Perform base runs on dedicated hardware (#3311)
- [x] Add performance (code duration) logging to the 0.17.x Composer stream (#2672)
- [ ] Enable overnight runs of all performance tests, with results being checked against a 'known good' level to enable determination of performance regressions on a dedicated machine
- [ ] Conditionally enable AppMetrics within chaincode containers
- [ ] Addition of performance metrics to base documentation

## Copyright

This document is licensed under the Creative Commons Attribution 4.0 International Public License.
