### ISSUE TITLE
Proposed items for 0.16.4

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3142]
**Items for 0.16.4:**

- [x] 1.  Bump version to 0.16.4! #3142  - Required in 0.16.x only

- [x] 2. Automatic version bump broken in v0.16.x branch #3128  - Required in 0.16.x only

- [x] 3. Cloud foundry deploy failing in builds #3153  - Required in 0.16.x and Master

- [x] 4. Provide HSM support for the 0.16.x code stream  #3245  - Required in 0.16.x and Master

- [x] 5. Documentation requried for playground when interacting with real fabric  #3165  - Required in 0.16.x and Master

- [x] 6. Documentation for network deploy is not correct  #2951  - Required in 0.16.x

- [x] 7. Composer network deploy CLI has lost capability #2952  - Required in 0.16.x

- [x] 8.  If a card fails to import and gives an error, the card is still actually imported #3275  - Required in 0.16.x

- [x] 9. Reinstate optional Usabilla survey/tracking to playground #3334 - Required in 0.16.x and Master

- [x] 10. Stable: Remove the 0.16.0 release Banner from the landing page of Composer docs #3298 - required in 0.16.x

- [x] 11. Composer network upgrade should not require the business network name in the card #2891 - Required in 0.16.x and Master

- [x] 12. Connect profile reference issue #2924 (via #3245 work) - Required in 0.16.x and Master

**Items that may be delivered depending on release date of 0.16.4:**
- [ ] A. None

**Comment by jt-nti** [comment]
Manual version bump delivered in PR #3127

**Comment by lesleyannjordan** [comment]
Deliveries:
1. #3142 Bump version to 0.16.4!  - PR #3127
2. #3128 Automatic version bump broken in v0.16.x branch  - PR #3164
3. #3153 Cloud foundry deploy failing in builds  - PR #3266
4.
5.
6. #2951 Documentation for network deploy is not correct - PR #3269
7. #2952 Composer network deploy CLI has lost capability - PRs #3267 #3268

**Comment by lesleyannjordan** [comment]
0.16.4 complete
