### ISSUE TITLE
Install business network as Fabric chaincode

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3218]
**As a** business network deployer
**I want** to deploy business networks as Fabric chaincode
**so that** the business network (rather than Composer runtime) can be agreed by all parties and signed, using a similar management model to non-Composer chaincode

## Tasks
- [x] Remove `composer runtime install` command and API.
- [x] Create `composer network install` command and API to install the BNA onto the peer:
    - Unpack the BNA. This may require a `BusinessNetworkDefinition.toDirectory()` function.
    - Update `package.json` to include required dependencies.
    - Use node packager to package up and send to the peer.
- [x] Update `composer network start` command to take the name and version of the business network to be started.
- [x] Remove `composer network deploy` (otherwise it needs to updated to provide identical behaviour with new deployment process).
- [x] Runtime changes required to remove the BNA being stored in the world state and the caching of the compiled BNA. The BNA will be loaded from disk and cached into memory at chaincode container start time as well as change slightly how chaincode gets started from the BNA's `package.json`
- [x] Refactor system and integration tests for new deployment model.
- [x] Doc updates for CLI changes

**Comment by dselman** [comment]
Can you please describe:
- the UX impact on Playground, if any
- changes to the ACLs, for example for network operations
- the UX and management model for non-Composer chaincode. E.g. concretely how are network participants supposed to coordinate install and verification across their peers

**Comment by davidkel** [comment]
@bestbeforetoday as part of the removal of deploy. There is some docs about deploy here
https://hyperledger.github.io/composer/next//managing/connector-information
You might not spot one of them because there is an error on the page which talks about composer network start for the npmrc file where it should have said composer network deploy

Also another thought has occurred to me. The composer-connector-hlfv1 declares a dependency on the `composer-runtime-hlfv1`, however with this change it doesn't require that dependency anymore and it would be really good to take it out as the composer-runtime-hlfv1 depends on the fabric-shim which pulls in a native library called x509. This currently burdens the composer-cli with more packages and a native compilation which are never used and removing this dependency will resolve this issue nicely

**Comment by davidkel** [comment]
@dselman In answer to your questions
- there will be an impact on playground when working with a real fabric. see https://github.com/hyperledger/composer/issues/3241
- there should't be any impact to ACLs, the business network will still work the same way
- not sure I understand the final question

**Comment by arnabmitra** [comment]
I am guessing this is going to be released soon? any ideas about the release date??

**Comment by bestbeforetoday** [comment]
I am expecting to see it go out in a Composer release (likely 0.19.0) this week.
________________________________
