### ISSUE TITLE
Upgrade business network deployed as Fabric chaincode

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3233]
**As a** business network deployer
**I want** to upgrade an installed business network to a new version
**so that** I can put new application capability or fixes into production

Upgrade process would be to:
1. Install the new version of the business network (alongside the previous version).
1. Run the upgrade command to replace the previous with the new version as the running business network.

## Tasks
- [x] Remove `composer network update` command.
- [ ] Change _Init_ handling to record Composer runtime version in blockchain on first start (within some _started_ record).
- [ ] Change _Init_ handling to check for existing runtime for the _started_ record (which will be present on an upgrade) and verify that new business network version being installed is valid (i.e. compatible with the previous version of business network and composer runtime).
- [x] Change `composer network upgrade` command to perform a version upgrade of an installed business network. Needs to invoke a Fabric _upgrade_ transaction, which is handled in the chaincode _Init_.
- [x] Integration test for upgrade.
