### ISSUE TITLE
Use REST server to access business network deployed as Fabric chaincode

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3236]
**As a** business network deployer
**I want** to expose by business network over REST
**so that** application clients can use this REST interface to drive business transactions

REST server needs to download the business network definition. Previously the BNA is held in world state; now it will be obtained from disk on the peer (since it is the running chaincode).

## Tasks
- [x] Update getBusinessNetwork() API.
- [x] Update `composer network download` CLI command.
- [x] Refactor embedded connector / runtime to match new runtime behaviour to enable unit tests.

**Comment by samjsmith** [comment]
I just managed to get the REST server up and running and also to use the `composer network download` command to export a running business network.  So I've ticked both of these items off.
Next up: embedded connector
