### ISSUE TITLE
Hardware security module support

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3244]
**As a** blockchain application architect
**I want** to use a hardware security module for all identities managed by Composer
**so that** I can provide a higher degree of security to management of credentials

HSM (Hardware Security Module) provides a way to keep private keys secure. Private keys are never transported outside of the HSM to ensure greater security.
PKCS#11 is a standard that HSMs can support to allow for applications a generic way to interface with an HSM.  
The fabric node-sdk has only had experimental support for PKCS#11 however there are imminent releases coming to fix problems with it and to make it more mainstream. With this pre-req Hyperledger composer will be able to exploit this, both in the 0.16.x branch targeting Fabric 1.0 and the master branch targeting Fabric 1.1

#3245 Provide HSM Support for 0.16.x code stream
#3246 Provide HSM Support for 0.17.x code stream

As part of this epic, the following need to be done
- [x] implement a prototype against the master code stream
- [x] implement a prototype against the 0.16.x code stream
- [x] add support to run the functional tests specific to identity as a separate tasks in association with softhsm 2.0.0 for 0.16.x
- [x] add support to run the functional tests specific to identity as a separate tasks in association with softhsm 2.0.0 for master
- [x] include new integration tests that drive the cli to perform identity management in association with softhsm 2.0 for 0.16.x
- [x] include new integration tests that drive the cli to perform identity management in association with softhsm 2.0 for master
- [x] test prototype against node-sdk code that will be delivered for 1.0
- [x] test prototype against node-sdk code that will be delivered for 1.1
- [x] setup Hardware HSM capable of interacting with Composer and set up client side in order to communicate with the Hardware HSM

**Comment by davidkel** [comment]
Closing as this is done for now.
