### ISSUE TITLE
Integration test of Playground when using Fabric

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3307]
We currently have automated testing of Playground, using the web-store.

We should also be targeting the testing of Playground when interacting with fabric for some key scenarios. This will require a more elaborate test run, mixing Fabric deployment and configuration (we should be using the composer tooling that we provide) and the subsequent spawning of Playground, driven by Protractor.

Scenarios that should be tested include:

- [x] Creation of sample network
- [x] Update of assets in deployed network
- [x] IDCard round trip between runtime (via CLI) and Playground

Some really interesting considerations here relate to being able to orchestrate the playground/cli command interactions required during the protractor testing to enable the round trip process.

**Comment by nklincoln** [comment]
kudos to @awjh-ibm 🎉
