### ISSUE TITLE
Improve/complete the business network generator

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#3385]
There is a business network generator that can be used to generate a skeleton business network.
You can run this by using Yeoman: `yo hyperledger-composer:businessnetwork`

Combining all of the work that needs doing to the business network generator into a single issue so it's tracked in one place, until somebody finds the time to do it:

- [ ] Provide BDD style/Cucumber tests in generated business network (was #1175)
- [x] Ensure linting configuration is up to date and works correctly (was #2766)
- [ ] Add permissions.acl and queries.qry files to generated business network (was #3176)
- [x] Add a better generated README.md (was #3300).
- [x] Add unit tests for the busnet generator 😡 

There is also an outstanding test debt issue for an automated integration test which will need to be completed or extended in order to close out this work (is #3306). Leaving the test debt issue open as it can be done without doing this work, but this work cannot be done without doing the test debt 😉
