### ISSUE TITLE
Proposed items for 0.16.6

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/composer#3482]
**Items for 0.16.6:**

 - [x]   1. Manual version bump to 0.16.6 #3482 - Required in 0.16.x only

 - [x]   2. Automatic version bump broken in v0.16.x branch #3128 - Required in 0.16.x only

 - [x]   3. New Node-RED Tutorial #3492  (Previously **PR #3352 - Revert PR #3481**) - Required on 0.16.x

 - [x]  4. Composer Network Deploy - Docs Inconsistent #3494 - Required 0.16.x and master

- [x] 5. fix rest server inability to import cards with certs #3555
 
- [x] 6. update to node sdk 1.0.5 #3556  

**Items that may be delivered depending on release date of 0.16.6:**

 - [x]   A. NPM modules contain all the unit tests, scripts dir #3430 - Closed out, due to no reported problems for 0.16.x

**Comment by lesleyannjordan** [comment]
Deliveries:

1. Manual version bump to 0.16.6 **PR #3487**
