### ISSUE TITLE
Proposed items for 0.16.7

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/composer#3573]
**Items for 0.16.7:**

-  [X]   1. Manual version bump to 0.16.7 #3573 - Required in 0.16.x only

 - [X]   2. Automatic version bump broken in v0.16.x branch #3128 - Required in 0.16.x only

 - [X] 3. Issue with @types/tapable breaking webpack in playground #3574 - Required in 0.16.x and master

 - [ ]  4.  Improve multi-org tutorial #3148 - Required in 0.16.x

 - [ ]  5. 0.16.x documentation requires updating away from 'latest' tag #3720 - Required 01.6.x only

**Items that may be delivered depending on release date of 0.16.7:**

 - [ ]   A. Data Collection Tool #3051 - Required in 0.16.x and Master

 - [ ]   B. Code example for post in TP #3188 - Required in 0.16.x

**Comment by lesleyannjordan** [comment]
Delivered items:
1.  #3573 Manual version bump to 0.16.7 **PR #**
2. #3128 Automatic version bump broken in v0.16.x branch   **PR #3577* Automatic verion bump fix for v0.16.x
