### ISSUE TITLE
Serverless Rest API

### ISSUE THREAD

**Issue by marckaraujo** [hyperledger/composer#3950]
## Serverless Rest API
This a Serverless Rest API Demo Project

## Motivation
Serverless Functions bring to us scalability and micro services.
With this you wont need to:

- Config Load balance
- Manage Multi servers
- And reduce costs...

## Github Project
https://github.com/mataide/serverless-hyperledger

## Tasks TODO

- [X] Setup AWS Lambda
- [X] Define Modules
- [X] Create a Model
- [X] Define $HOME Env
- [ ] Reduce Package to 50Mb
- [ ] Config Loopback
- [ ] Write Documents

**Comment by mbwhite** [comment]
Thank you for letting us know about this;  this is something that I've also tried using OpenWhisk (that I'm still writing up). 

Will take a look at your repo.

**Comment by mbwhite** [comment]
@marckaraujo  ... however we will need to close this issue - as it's not a Composer Defect or Request for enhancement;  

Please keep us updated on what you do - perhaps sharing on a community call?

**Comment by marckaraujo** [comment]
@mbwhite, thanks for the recognition, I just wanted to post it here, so people can find this project.

I'd like to ask you a help with loopback.
I didn't find anyway to configure loopback connector programatically.
I'd like to use Dynamodb as database, I just find this project:
https://github.com/mandarzope/loopback-connector-dynamodb

Do you think that is possible? Have any hint?
