### ISSUE TITLE
As a user I can run a sample web application demonstrating the animal tracking business network

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#44]
- [ ] Port Mozart to use the latest Loopback code
- [ ] Put in place a system test to check Mozart is running
- [ ] Write a README that describes how to run the sample and what it shows

Code should live under:
- sample-applications, sample-networks and sample-models.

**Comment by dselman** [comment]
Is this blocked by something?

**Comment by 14gracel** [comment]
TODO: 
- [ ] Regulator view
- [ ] Move to use bootstrap 4 to improve modal support
- [ ] Fix search pipes

**Comment by EdMoffatt** [comment]
Just gonna pop this over onto the Playback 4 milestone to clear out Playback 3...

**Comment by sstone1** [comment]
@14gracel I know you did _some_ work on this, where is the result of that work? In your fork?
@dselman I'd like to propose we just close this off and focus on the vehicle lifecycle network for now, and re-visit animal tracking if/when we feel like spending the resource on it.
