### ISSUE TITLE
As a user I would like to create a model and publish it for reuse by networks and other models

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#579]
To support the emergence of an ecosystem of models (and ultimately a model catalog) users need to be able to easily import types from external namespaces.

Example scenario:

1. Paul develops a model for a business domain, based on government regulations
2. Paul pushes the model to a GitHub repo
3. Jane wants to develop a model that imports elements from the model created by Paul
4. Jane pushes her model to a GitHub repo
5. Utpal wants to build a business network based on the model published by Jane
6. Utpal references Jane's model and can write TP functions/ACLs
7. Utpal can import his business network into the Playground and test
8. Utpal can use the rest of the Composer tools with his business network

Places where we resolve types/namespaces:

- [ ] ModelManager.resolveType
- [ ] ModelFile.validate (imports)
- [ ] ModelFile.resolveType

## High-level Design

A set of `ModelLoader` implementations are associated with the `ModelManager`. Each `ModelLoader` is capable of loading a model based on a URL pattern.

A new `downloadExternalModels` method on the `ModelManager` walks all `ModelFiles` (prior to validation) and gets all `imports` that have a `from` declaration. Each external import is downloaded using the `ModelLoaders` (dispatching based on URL), parsed as a `ModelFile`, tagged as external and added to the `ModelManager`.

The `ModelManager` is them validated.

The `ModelManager` is updated to automatically tag `ModelFiles` as external if the namespace of the `ModelFile` is referenced by another `ModelFile` using a `from` import declaration.

`downloadExternalModels` is called when creating a BNA from a directory. This ensures that when the `toArchive` method is called the downloaded model files will be present, and that the BNA will validate if it us using external models. 

To update the model files explicitly a new method `updateExternalModels` is added to BusinessNetworkDefinition. This method removes all existing external `ModelFiles`, calls `downloadExternalModels` on the `ModelManager` and then validates.

### Should imports be self-describing, e.g. import from a URL?
Yes.

### What if the URL changes?
It will break the CTO file as the import will fail to resolve and we will get an exception during resolution.

### How is the URL related to the namespace of the model file?
It is explicit, using a new optional `from` element in the grammar

### How is model versioning handled?
The URL is sufficiently extensible that a version can be encoded in it

### Does the author have to import twice, once in `package.json` for the dependency and once in the model file for the actual import?
No, model imports are not declared in package.json, as models do not have to be npm modules

### Should the download of a model file from URL be separate from the resolution of the type?
Yes, models are transitively downloaded when the BNA file is built. Downloaded models are stored in the BNA statically under an `external-models` folder. This needs some more design, but the principle is that the runtime should not dynamically load models from external URLs.

### How does this relate to `npm` modules, GitHub releases or other repositories?
The ModelResolver is sufficiently general that implementations for other repositories could be created.

### Should we use a modelLocation / namespace pair, like XML Schema
Basically yes, as it makes the source of the namespace explicit

Example:

```
import org.acme.foo from https://acme.org/foo.cto
```

The proposal is to refactor this code to use a `ModelLoader` class, what could be set on the `ModelManager`.

An HTTP GET implementations of `ModelLoader ` would be created that loads the model file from a URL using an HTTPS GET. The URL prefix is used to dispatch to the `ModelLoader`, with https being routed to the HttpsModelLoader.

Note that `ModelFiles` that are loaded by the `ModelLoader ` would have the property `isExternal` set to true, all other `ModelFiles` would have the property set to false. The `isExternal` property can be used by tools to prevent these model files from being edited or persisted for example.
`ModelManager.updateModelFile and deleteModelFile` must throw an exception for external models.

The property `source` on the ModelFile will be set to the URL that the `ModelFile` was loaded from if the ModelFile was loaded from a URL, or null otherwise.

```
class ModelLoader {
 accepts(url) // returns true if the ModelResolver accepts this URL
 load(url) // returns a ModelFile for a URL
}
```

Example:

```
const mm = new ModelManager();
const l1 = new HttpsModelLoader();
mm.addModelLoader(l1);
const l2 = new GitHubReleaseModelLoader();
mm.addModelLoader(l2);
```

```
namespace org.acme

// HTTP import
import Foo from https://mydomain/foo.cto

// Loads the file bar.cto from the release archive for tag 0.0.6
import Bar from github://accordproject/cicero-template-library/releases/tag/0.0.6/bar.cto

```

## Required Changes

- [x] Hook loading of the external models into `BusinessNetworkDefinition.fromDirectory()` code.
- [x] Hook loading of the external models into `BusinessNetworkDefinition.fromArchive()` code.
- [x] Write tests
- [x] Create HttpModelLoader implementation and tests
- [x] Create GitHubReleaseModelLoader implementation and tests
- [x] Extend the CTO grammar to include an optional `from` statement for imports
- [x] Update Playground to prevent editing external model files (they should be read-only)
- [x] Ensure updateModelFile and deleteModelFile throw exceptions for external models

### Appendices

* Go package management: https://golang.org/doc/code.html
* XML Schema locations: https://msdn.microsoft.com/en-us/library/ms256100(v=vs.110).aspx?

**Comment by dselman** [comment]
Added some sample modes here: https://github.com/fabric-composer/sample-models

We now need to enable the `package.json` for a model to reference another published model, and have it pulled into the BNA when you call `BusinessNetworkDefinition.fromDirectory`

**Comment by dselman** [comment]
Model modules can now declare dependencies in package.json and `BusinessNetworkDefinition.fromDirectory` will follow the dependencies to build a valid archive. 

The Playground code needs to be updated to be able to import such networks from GitHub.

**Comment by dselman** [comment]
I backed out my changes (which broke `composer archive create` for lerna hoisted packages) so we currently cannot create BNA from those projects. We also need to make Playground smart enough to follow those dependencies. HOWEVER, we have a bit of an issue in that Playground will build the network "from source" pulling from github, while `composer archive create` will build it from npm (via an npm install). So, that needs some architecture thinking...

**Comment by EdMoffatt** [comment]
Pulling this into the Phase 2 Milestone as something for Design to start looking into.  Also assigning to myself to start figuring out what's needed.
Likely to be linked to a rework of import behaviour from within the Edit view (to bring it more in line with the new improved designs we're seeing with new network deploy from the My Wallet screen).

**Comment by dselman** [comment]
# Documentation

## Importing Models from External Sources

An `import` declaration in a CTO file may optionally include a `from` declaration to indicate that a namespace, type or types should be includes from a model file hosted externally. Currently, model files hosted on `GitHub` and on HTTP(S) servers are supported.

### Importing a type from a model file hosted on GitHub

The GitHub URL is of the form: `github://<org>/<repo>/<branch>/<path>`

```
import org.accordproject.address.PostalAddress from github://accordproject/models/master/address.cto
```

### Importing a type from a model file hosted on an HTTP or HTTPS server

HTTP and HTTPS URLs may be used as-is to load model files:

```
import org.accordproject.address.PostalAddress from https://myserver.com/mypath/mymodel.cto
```

## Download External Models

### Using the CLI

Models that are imported from external sources (external models) may be automatically downloaded when the business network archive is created by passing the `--updateExternalModels` option to the `composer archive create` CLI command. Please refer to the help of the command for additional details.

When this option is specified all external models are downloaded and placed within the `/models` folder of the business network archive. External models are statically packaged within the archive to ensure that external model resolution never takes place at runtime.

### Using API

Pass the value `updateExternalModels` to the `BusinessNetworkDefinition.fromDirectory` method in the `options` parameter to create a `BusinessNetworkDefinition` in memory from a root directory; including downloaded external model files. In addition the value `updateExternalModelsOptions` may be passed to specify additional download specific options, such as authorization headers.

For finer-grained control of the download and update process the `ModelManager.updateExternalModels` method may be used. Please refer to the API documentation for details.

**Comment by dselman** [comment]
@EdProsser see documentation addition above.
@EdMoffatt needs some thinking on how we/if we integrate with Playground
