### ISSUE TITLE
As a user I have a Vehicle Lifecycle Demo

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#622]
## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by markcastle3** [comment]
@14gracel do we need to link any issues against this?
