### ISSUE TITLE
Playground component wishlist

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#649]
Collection of Angular components that could be useful for developing the Playground UI. This issue is to keep track of initial discussion before discounting any proposed components or moving them into their own issue.

- [ ] (01) SpinnerButton - there are already a few occurrences of the following pattern which it would be nice to simplify with a new component

```
<button type="button" class="primary" (click)="addOrUpdateResource()" [disabled]="definitionError!=null || actionInProgress ">
  <div *ngIf="!actionInProgress">
    <span>{{resourceAction}}</span>
  </div>
  <div *ngIf="actionInProgress" class="ibm-spinner-indeterminate small loop">
    <div class="loader">
      <svg class="circular" viewBox="25 25 50 50">
        <circle class="circle-path" cx="50" cy="50" r="20"/>
      </svg>
    </div>
  </div>
</button>
```

- [ ] (02) TypeaheadDropdown - dropdown with typeahead support (required for #533)

![pasted image at 2017_04_10 02_31 pm](https://cloud.githubusercontent.com/assets/3535067/24864481/4533cbf4-1dfc-11e7-89dc-58ca3516dba9.png)

- [ ] (03) Wizard - handle multi-step modals (required for #533)

- [x] (04) PopoverMenu - navigation item that opens a dropdown menu (required for identities, #533, footer, #440 etc.) - **Nick**

![image](https://cloud.githubusercontent.com/assets/3535067/24865565/8b58e0f8-1dff-11e7-8fc0-d98db89a0222.png)

- [ ] (05) SideNav - sidebar navigation/menus across the current pages are somewhat inconsistent

- [x] (06) Slide-in menu - 'menu'/dialog that slides in from the side of the screen, e.g. from #1415 - **JT**

![image](https://user-images.githubusercontent.com/3535067/27792838-70b1c478-5ff3-11e7-92cb-21608374e2dc.png)

**Comment by sstone1** [comment]
Six months since last update, closing!
