### ISSUE TITLE
Test Improvements for Composer Playground

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#658]
Composer Playground test improvements, following from #449 and #435

## Context
The existing tests for Composer Playground components need to be extended to include UI display/logic checks appearing correctly at the DOM level. The ts files appear to be tested rigorously, though there appears to have been a focus on code coverage for the typescript file and no real focus on testing the intent from a user perspective. For instance there are unchecked links to the rendered UI that can result in breakages should the underlying ts file get changed without a corresponding change being made on the html file.

This is not about using Protractor to verify an end-to-end user experience, but about extending the existing Karma/Jasmine tests to include inspection of the DOM tree for the component under test and ensuring that the typescript logic facilitates the required/desired user intention.

## High Priority Additions
- [x] Remove test logging output **Nick**
- [x] Stop downloads occurring within tests **Nick**
- [ ] Drag Drop Directive test coverage improvements (#849)
- [ ] Extend connection profile tests (#841) **Jake**
- [ ] Angular generator tests (#824) **Jake**
- [ ] Services: improve coverage in about/client/wallet services, (#848)
- [x] Add Certificate Component **Nick**
- [x] Add Identity: enable/add tests
- [x] Admin Service **Caroline**
- [x] Connection Profile Component **Sam**
- [x] Connection Profile Data Component **Jake**
- [x] Connection Profile Service **Mark**
- [x] Delete Connection Profile Component **Sam**
- [x] Editor: Complete TODO for openExportModule **Nick**
- [x] Editor: edit package options and interaction **Nick**
- [x] Resource/Transaction component: button disabled/enabled check on definition error; definition error message displayed/removed; processing icon shown on submit; generate random selection works. **Nick**

## Medium Priority Additions
- [ ] Error: extend tests (#850)
- [ ] Editor File: correct message (Error/OK) displayed in UI for CTO, JS, ACL file content (#851)
- [ ] Registry: UI displays correct registry type and namespace, Add button labelled with correct addition, button not present for Transaction types (#852)
- [ ] Services: improve coverage in admin/connection/initialisation/sample services, (#848)

## Low Priority Additions
- [ ] Add File: Button logic (#854)
- [ ] Import: button disabled/enabled check (#854)

**Comment by jthub** [comment]
Moved identity test todo list to #533

**Comment by nklincoln** [comment]
Moved connection profile test todo list to #752

**Comment by markcastle3** [comment]
@nklincoln looks like you are split this out into separate issues, do you need some helping doing this ?

**Comment by nklincoln** [comment]
@markcastle3 - now that all points have an assigned issue, shall we close this one?

**Comment by sstone1** [comment]
@nklincoln yes we shall.
