### ISSUE TITLE
As a user, I can publish and subscribe to business events within a business network

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#66]
As a business network developer, I want to be able to publish custom business events from my transaction processor functions so that I can notify applications and existing business processes of _interesting_ business events (for example, that a vehicle has been transferred).

As an application developer, I want to be able to subscribe to all business events emitted by a business network from a JavaScript applications using the `composer-client` APIs so I can use them to notify users, kick off existing business processes, or feed them into analytics tools.

We will update the modelling language to allow a business network developer to model custom business events as they would concepts, assets, etc. For example:

```
event MyEvent identified by eventId {
   o String eventId
   o Double data
   --> Person owner
}
```

- [x] Extend modelling language to support events #756
- [x] Extend the Visual Studio Code extension to support events #807

We will extend the runtime API to allow a transaction processor function to create a new event using `factory.newEvent` and emit them using `emit`:

```
// Create new event.
let event = factory.newEvent('org.acme', 'MyEvent');

// Populate the event.
event.data = 1.234;
event.owner = factory.newRelationship('org.acme', 'Person', '1234');

// Emit the event.
emit(event);
```

The event ID will be automatically set by either the factory or the emit method. The event ID will be a combination of the transaction ID and an automatically incrementing integer.

The runtime will internally change to add a new event service. The Blockchain specific implementations of the event service will handle the publication of the events, for example using the Hyperledger Fabric chaincode APIs.

- [x] Factory changes to create instances of an event
- [x] Runtime changes to emit an event in the Hyperledger Fabric v1.0 runtime #870
- [x] Runtime changes to emit an event in the web runtime #868 
- [x] Runtime changes to emit an event in the embedded runtime #869

We will extend the client API to allow a user to subscribe to events:

```
// Create new business network connection.
let businessNetworkConnection = new BusinessNetworkConnection();

// Subscribe to events.
businessNetworkConnection.on('event', (event) => {
  console.log('business event received', event);
});

// Connect to the business network.
return businessNetworkConnection.connect('profile', 'biznet', 'admin', 'adminpw')
  .then(() => {
    ...
  });
```

The BusinessNetworkConnection class should be modified so that it becomes an instance of EventEmitter to support this functionality. We should not go and build our own JavaScript event emitter implementation.

The connector API also needs to be updated so that each connector can subscribe to events using the Blockchain platform specific APIs. Suggest that the Connector class should also be modified so that it becomes an instance of EventEmitter to support this functionality.

As a **future** change, we could publish other events from the BusinessNetworkConnection and Connector class such as `connected` and `disconnected`.

We then need to document the modelling language and APIs, along with how to use them (a tutorial perhaps?):
- [x] Documentation for modelling, publishing, and subscribing to events #763 

Work not in scope for this user story, but possible extensions later on:
- Subscribing to events using the REST server (via websockets or webhooks)
- Access control around publishing/subscribing to events
- Publishing events through the playground UI for testing purposes

**Comment by dselman** [comment]
PR #361

**Comment by caroline-church** [comment]
@sstone1 can you break this down into stories please

**Comment by sstone1** [comment]
@14gracel there are some missing tasks/stories for each checkbox; please can you raise these or combine them into existing issues? Thanks!
