### ISSUE TITLE
Rebrand website and documentation to reflect Hyperledger Composer naming

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#724]
All content on this website [http://fabric-composer.github.io](http://fabric-composer.github.io) needs to reflect our new name, Hyperledger Composer, now that we are officially part of Hyperledger. Further issues will be raised for the rebranding of the Playground etc.

Related:
[#725 Rebrand playground to reflect Hyperledger Composer naming](https://github.com/hyperledger/composer/issues/725)

I am working on determining where the website will live in terms of URLs and how it will get published there, but this work can continue whilst those discussions are still happening.

Whoever takes on this work must read these documents provided by Hyperledger:

Hyperledger Brand Guidelines are here: [Google Docs](https://docs.google.com/presentation/d/1VtDLyFmrkjpaHeqXCJQzuP4eyx1rTTzZwtq9RsvL1dM/edit#slide=id.p4)
Hyperledger Trademark Usage Guidelines are here: [Google Docs](https://www.hyperledger.org/trademark-usage)

We need to take our time and do a thorough job of checking the documentation; there are lots of mentions of Fabric Composer to update, but we should also be looking for HL (no abbreviations), HyperLedger (incorrect capitalisation), IBM (no longer relevant 😉), etc. which I am sure are lurking in the docs. I suspect that regex-fu is not going to be enough.

We also need to find and update any links that refer to Fabric Composer, e.g. GitHub repository URLs.

We're also not great at getting other product names right, for example: [https://fabric-composer.github.io/support/index.html](https://fabric-composer.github.io/support/index.html)
Rocket Chat = Rocket.Chat (dot, capital C)
Github = GitHub (capital H)
Stackoverflow = Stack Overflow (space and capital O)
Javascript = JavaScript (capital J and S)

Can we clean these up throughout the docs whilst we're at it please?

I am trying to find somebody in the Hyperledger team that can review the updates once ready.

**Comment by EdProsser** [comment]
I've created a conref in all the documents I've edited which controls the product name, it won't catch them all, but I can change that variable, then use a find and replace to get the rest and add the conref variable there as well. 

Glad that putting that variable in turned out to be a good idea ^^

**Comment by winslet** [comment]
Website done: https://github.com/hyperledger/composer/pull/737

**Comment by EdProsser** [comment]
@sstone1 All references are done in the docs. I've left links intact, as I'm not sure of their new addresses, and references in codeblocks as we don't want to tell people incorrect commands. Have been speaking with @mbwhite about the code references. Does this Issue also refer to ALL other website mentions of Fabric Composer?

**Comment by EdProsser** [comment]
As the docs side of this is done, I'm unassigning myself for now. :)

**Comment by EdProsser** [comment]
@sstone1 Is there anymore work which needs doing related to this, or can it be closed?

**Comment by EdMoffatt** [comment]
This one isn't done yet.  It's sort of acting like an Epic really - there are a bunch of things included in completing this one that we still need to close out...

- [ ] Update all social links, hashtags, stack overflow tags etc. in docs, homepage and community page (extending the work on #737 )
- [ ] Close out #725 to make all the identified required changes in the Playground
- [ ] Find and fix any references in the samples - #729

Actually, there's also the plug-ins etc. etc.  I see now I've started writing this list that it's basically just "all the Issues referenced in here"!

**Comment by winslet** [comment]
fix for first bullet above going in on PR #809

**Comment by nklincoln** [comment]
Also need to go through all *.md files - #835

**Comment by winslet** [comment]
Looks like the above is all done. Going to close out.

**Comment by 14gracel** [comment]
- [ ] https://www.npmjs.com/package/composer-cli still needs rebranding
