### ISSUE TITLE
As a user, I want to query a world-state in CouchDB with JS API via Composer

### ISSUE THREAD

**Issue by fenglianxu** [hyperledger/composer#820]
This is a first step of the epic #543 to set up an example of business network and deploy it on the current released composer that runs the HLF V1 alpha 2 or beta release, then create some sample data, and finally query data via Couch DB. 

This story is a starting point to test and workout the steps for config couchDB and create data, and query data with Couch DB. 

This story is to define a JS API for query for Client application to query world state data from CouchDB.  
The state data includes:

- assets

- participants

- transactions

 Ledger rich data query

- queryString = {"selector" : { "owner": "dan"}

- GetQueryResult(queryString)

 
## Expected Behavior

Should be able to query the current block status from the data you created in the blockchain. 
Should be return a response message with details when there is no data found.

## Tasks
1.  Enable CouchDB in HLFV 1
2. Setup a sample application with HLF V1 to create some assets using vehicle life cycle business network
3. Run query test with curl command line
4.  Define API in composer runtime module
5.  Testing API.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used: HLFV1 alpha release or latest stable 
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by fenglianxu** [comment]
This story is split into below steps:
1.  Enable CouchDB per peer in composer-sample-applications and system test
2. Run a vehicle life cycle to create some data inside couchDB
3. create a  few sample queries to run from command line or couchDB.

**Comment by fenglianxu** [comment]
This story is done and wait for merge to the master code stream.

**Comment by dselman** [comment]
This was delivered in v0.8
