### ISSUE TITLE
As a user I would like to see more participants in the Vehicle Lifecycle Demo

### ISSUE THREAD

**Issue by markcastle3** [hyperledger/composer#918]
## Context
1) Addition of another participant - auction house or different manufacturer
2) have the scrap merchant view via the automated UI generator - in later lab user will create this themselves. 
3) find a very simple transaction a user can create (model & script) for them to then create the API for and use - eg change colour of car?

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sstone1** [comment]
Not actionable, closing.
